config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: [:index, :show]
  resources :movies, only: [:index, :show]
  resources :comparisons, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comparison.rb
class Comparison < ApplicationRecord
  
  belongs_to :superior_movie, class_name: "Movie"
  belongs_to :inferior_movie, class_name: "Movie"
  
  belongs_to :user
end

app/models/movie.rb
class Movie < ApplicationRecord

  has_many :superior_comparisons, foreign_key: :superior_movie_id, class_name: "Comparison"
  has_many :inferior_movies, through: :superior_comparisons

  has_many :inferior_comparisons, foreign_key: :inferior_movie_id, class_name: "Comparison"
  has_many :superior_movies, through: :inferior_comparisons
  
  has_many :fans, through: :superior_comparisons, source: :user
  has_many :haters, through: :inferior_comparisons, source: :user
end

app/models/user.rb
class User < ApplicationRecord

  has_many :comparisons
  
  has_many :inferior_movies, through: :comparisons
  has_many :superior_movies, through: :comparisons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comparisons_controller.rb
class ComparisonsController < ApplicationController
  
  def create
    user = User.find(params[:user][:id])
    Comparison.create(user_id: user.id,
                      superior_movie_id: params[:comparison][:superior_movie_id],
                      inferior_movie_id: params[:comparison][:inferior_movie_id])
    redirect_to user_path(user)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  def index
    @movies = Movie.all
  end
  
  def show
    @movie = Movie.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @movies = Movie.all
    @comparison = Comparison.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comparisons_helper.rb
module ComparisonsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieComparisonApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<h1>Movies index page</h1>

<% @movies.each do |movie| %>
  <h2><%= link_to movie.title, movie_path(movie) %></h2>
<% end %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>
<h2><%= @movie.year %></h2>

<small><%= link_to "Back to all movies", movies_path %></small>

<h3> Victorious comparisons: </h3>
<ul>
  <% @movie.superior_comparisons.each do |comparison| %>
  <li><%= comparison.user.name %> likes this movie more than <%= comparison.inferior_movie.title %></li>
  <% end %>
</ul><br>

<h3> Losing comparisons: </h3>
<ul>
  <% @movie.inferior_comparisons.each do |comparison| %>
  <li><%= comparison.user.name %> thinks that <%= comparison.superior_movie.title %> is better </li>
  <% end %>
</ul><br>

app/views/users/index.html.erb
<h1>We're live.</h1>

<% @users.each do |user| %>
  <h2><%= link_to user.name, user_path(user) %></h2>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<small><%= link_to "Back to all Users", users_path %></small>

<h2>Movie Comparisons</h2>

<table>
  <thead>
    <tr>
      <th>Superior Movie</th>
      <th>Inferior Movie</th>
    </th>
  </thead>
  <tbody>
    <% @user.comparisons.each do |comparison| %>
      <tr>
        <td><%= comparison.superior_movie.title %></td>
        <td><%= comparison.inferior_movie.title %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Create new comparisons</h2>

<%= form_for @comparison do |f| %>
  <input type="hidden" name="user[id]" value="<%= @user.id %>">

  <%= f.label :superior_movie_id, "Superior movie" %>
  <%= f.collection_select :superior_movie_id, @movies, :id, :title %><br>

  <%= f.label :inferior_movie_id, "Inferior movie" %>
  <%= f.collection_select :inferior_movie_id, @movies, :id, :title %><br>

  <%= f.submit %>
<% end %>